make PKCE easier
golang/oauth2 pull request #625
Opened 2023-01-28 15:02 UTC by hickford

2023-02-06 05:01 UTC, J0 commented
Hey 

I'm a user of this package and just wanted to say that better PKCE support would be a great plus for me. Thanks for putting this together and hope this goes through!

2023-05-21 20:37 UTC, jkroepke commented on oauth2.go
> +`345432Q// Client returns an HTTP client using the provided token.
```suggestion
// Client returns an HTTP client using the provided token.
```
seems like type into a wrong window focus

2023-05-22 05:34 UTC, hickford commented on oauth2.go
> +`345432Q// Client returns an HTTP client using the provided token.
Thanks fixed

2023-06-19 07:41 UTC, wzy9607 requested changes

2023-06-19 07:41 UTC, wzy9607 commented on pkce.go
> +	challenge := base64.URLEncoding.EncodeToString(sha[:])
RFC requires the no padding version of base64 url encoding.

https://datatracker.ietf.org/doc/html/rfc7636#section-3

2023-09-07 17:56 UTC, closed without merging