fix(filecredsource.go): improve error message in subjectToken function to include the actual error detail
golang/oauth2 pull request #749
Opened 2024-10-22 17:05 UTC by kaovilai

2025-01-05 11:49 UTC, peick requested changes

2025-01-05 11:49 UTC, peick commented on google/externalaccount/filecredsource.go
> +		return "", fmt.Errorf("oauth2/google/externalaccount: failed to open credential file %q due to %v", cs.File, err)
a common pattern is to use `<text>: %v` instead. Suggested change:

```go
return "", fmt.Errorf("oauth2/google/externalaccount: failed to open credential file %q: %v", cs.File, err)
```

2025-01-06 05:11 UTC, kaovilai commented on google/externalaccount/filecredsource.go
> +		return "", fmt.Errorf("oauth2/google/externalaccount: failed to open credential file %q due to %v", cs.File, err)
```suggestion
		return "", fmt.Errorf("oauth2/google/externalaccount: failed to open credential file %q: %v", cs.File, err)
```

2025-01-11 10:16 UTC, peick approved these changes

2025-04-16 20:31 UTC, closed without merging