retrieveDeviceAuth: Call r.Body.Close()
golang/oauth2 pull request #750
Opened 2024-11-04 23:09 UTC by Miciah

Close the response body after reading it in the DeviceAuth logic.

The `retrieveDeviceAuth` function did not close the response body. However, the net/http documentation states that one is expected to close the response body after one sends an HTTP request and reads the response body.  In addition, [the `doTokenRoundTrip` function *does* call `r.Body.Close()`](https://github.com/Miciah/oauth2/blob/ffeca96aa76167a098068334a567bb7c0975acc8/internal/token.go#L255-L261).  (Some other functions use a client with [a custom Transport that automatically closes the body](https://github.com/Miciah/oauth2/blob/ffeca96aa76167a098068334a567bb7c0975acc8/transport.go#L30-L37), but that is not the case for `retrieveDeviceAuth` or `doTokenRoundTrip`.)

Follow-up to commit e3fb0fb3af0ee7c0c62e31c393cbcfce6b2af5bf.

---

I noticed the missing `r.Body.Close()` call while reviewing a vendor bump in a project that I help maintain.  This project doesn't actually use DeviceAuth; I was just skimming through the newly vendored code when I noticed the questionable logic.

2025-01-05 11:45 UTC, peick requested changes

2025-01-05 11:45 UTC, peick commented on deviceauth.go
>  	if err != nil {
it should be `defer r.Body.Close()` before reading all the content.

```
defer r.Body.Close()
body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
```

2025-01-24 21:02 UTC, Miciah commented on deviceauth.go
>  	if err != nil {
Hm, I'm not sure why we need to use `defer`, unless `io.ReadAll(io.LimitReader(r.Body, 1<<20))` can panic?  Anyway, I implemented your suggestion in https://github.com/golang/oauth2/compare/ffeca96aa76167a098068334a567bb7c0975acc8..8499b419ad4097ac16cd5b264b8efe53791ae259.  Thanks for reviewing!

2025-01-28 14:25 UTC, peick commented on deviceauth.go
>  	if err != nil {
Your solution is not wrong, but it's very common in golang to use the `defer reader.Close()` pattern.
A more precise version that can handle all kind of errors would be:

```
body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
if err != nil {
  r.Body.Close() // ignore _this_ error - we already have one
  ...
  return ...
}
err = r.Body.Close()
if err != nil {
  return ...
}
```

But this would make the code more unreadable. In most cases it is _ok_ to ignore the close error.

2025-04-16 22:53 UTC, closed without merging